version: 2.1

jobs:
  build:
    docker:
      - image: cimg/go:1.21.5
    steps:
      - checkout
      - run: 
          name: Build Go Application
          command: |
            cd cmd
            go build -o ../output ./main.go